[phases.setup]
nixPkgs = ["nodejs", "python311", "gcc"]

[phases.install]
cmds = [
    "npm install",
    "python3 -m pip install --upgrade pip",
    "python3 -m pip install -r requirements.txt"
]

[start]
cmd = "python3 gift_manager.py & node server.js"
