[phases.setup]
nixPkgs = ["nodejs-20_x", "python311", "gcc"]

[phases.install]
cmds = [
    "npm install",
    "python3 -m pip install -U telethon aiohttp python-dotenv"
]

[start]
cmd = "npm start & python3 gift_manager.py"
